# Use the latest 2.1 version of CircleCI pipeline process engine.

version: 2.1

commands:
  print_pipeline_id:
    description: "A simple command to print the pipeline id"
    parameters:
      to:
        type: string
    steps:
      - run: echo pipeline-id <<parameters.to>>

jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    docker:
      - image: "circleci/node:erbium-bullseye-browsers-legacy"
    # Add steps to the job
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: "npm-packages"
          paths: /src/node_modules
      - run: npm run lint

  test:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    docker:
      - image: "circleci/node:erbium-bullseye-browsers-legacy"
    # Add steps to the job
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run: npm install
      - run: npm run test

  analyze:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    docker:
      - image: "circleci/node:erbium-bullseye-browsers-legacy"
    # Add steps to the job
    steps:
      - checkout
      - run: npm audit
      - run: 
          name: Audit Fail
          command: npm audit fix
          when: on_fail 

# Orchestrate jobs using workflows
workflows:
  myworkflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test